// Progressive enhancement for the static library generated by tools/build.mjs (ADR 0001).
// Everything here is optional: with JS off, index.html is already the full, navigable library.
(() => {
  "use strict";

  const $ = (sel, root = document) => root.querySelector(sel);
  const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));

  const RECENT_KEY = "recent";
  const RECENT_MAX = 4;
  const THEMES = ["system", "light", "dark"];

  // ---------- storage (private mode / quota / disabled storage all throw) ----------

  function storageGet(key) {
    try { return localStorage.getItem(key); } catch { return null; }
  }
  function storageSet(key, value) {
    try { localStorage.setItem(key, value); } catch { /* non-essential state */ }
  }
  function storageRemove(key) {
    try { localStorage.removeItem(key); } catch { /* non-essential state */ }
  }

  // ---------- recently opened ----------
  // Rendered first, synchronously, because the head script already reserved space for it
  // (html.has-recent); filling it before anything else keeps CLS at zero.

  const recentSection = $("#recent");
  const recentList = $("#recentList");

  function readRecent() {
    let parsed;
    try { parsed = JSON.parse(storageGet(RECENT_KEY) || "[]"); } catch { return []; }
    if (!Array.isArray(parsed)) return [];
    // Accept bare strings too, so a hand-edited or older value doesn't wipe the list.
    return parsed
      .map((entry) => (typeof entry === "string" ? entry : entry && entry.id))
      .filter((id) => typeof id === "string" && id);
  }

  function writeRecent(ids) {
    if (ids.length) storageSet(RECENT_KEY, JSON.stringify(ids.map((id) => ({ id }))));
    else storageRemove(RECENT_KEY);
  }

  function rememberCourse(id) {
    const ids = [id, ...readRecent().filter((x) => x !== id)].slice(0, RECENT_MAX);
    writeRecent(ids);
    return ids;
  }

  function findCourse(id) {
    const el = id ? document.getElementById(id) : null;
    return el && el.classList.contains("course") ? el : null;
  }

  function buildRecentItem(course) {
    const open = $("a.btn--primary", course);
    const title = $(".course-title", course);
    if (!open || !title) return null;

    const li = document.createElement("li");
    li.dataset.id = course.id;

    const a = document.createElement("a");
    a.className = "recent-item";
    a.href = open.getAttribute("href");
    a.target = "_blank";
    a.rel = "noopener";
    a.type = "application/pdf";
    if (document.getElementById("newTabHint")) a.setAttribute("aria-describedby", "newTabHint");

    const cover = $(".course-cover", course);
    if (cover) {
      const img = document.createElement("img");
      img.className = "recent-cover";
      img.src = cover.getAttribute("src");
      img.width = 48;
      img.height = 64;
      img.alt = "";
      img.loading = "lazy";
      img.decoding = "async";
      a.append(img);
    }

    const name = document.createElement("span");
    name.className = "recent-name";
    // titleText(), not textContent: highlighting may have split the title into <mark> nodes.
    name.textContent = titleText(title);
    a.append(name);

    const metaSrc = $(".course-meta", course);
    if (metaSrc) {
      const meta = document.createElement("span");
      meta.className = "recent-meta";
      meta.textContent = metaSrc.textContent.replace(/\s+/g, " ").trim();
      a.append(meta);
    }

    li.append(a);
    return li;
  }

  function ensureRecentClearButton() {
    if (!recentSection || $(".recent-clear", recentSection)) return;
    const heading = $("#recentTitle", recentSection);
    if (!heading) return;

    const row = document.createElement("div");
    row.className = "recent-head";
    heading.replaceWith(row);
    row.append(heading);

    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "recent-clear link-button";
    btn.textContent = "Clear";
    btn.setAttribute("aria-label", "Clear recently opened");
    btn.addEventListener("click", clearRecent);
    row.append(btn);
  }

  function renderRecent() {
    if (!recentSection || !recentList) return;
    const stored = readRecent();
    const items = [];
    const live = [];
    for (const id of stored) {
      const course = findCourse(id);
      const li = course && buildRecentItem(course);
      if (li) { items.push(li); live.push(id); }
    }
    // Prune ids for courses removed in a later build so they never come back.
    if (live.length !== stored.length) writeRecent(live);

    recentList.replaceChildren(...items);
    const hasItems = items.length > 0;
    if (hasItems) ensureRecentClearButton();
    recentSection.hidden = !hasItems;
    document.documentElement.classList.toggle("has-recent", hasItems);
  }

  function clearRecent() {
    writeRecent([]);
    renderRecent();
    // The section (and the focused button) just vanished; land somewhere meaningful nearby.
    const q = $("#q");
    if (q) q.focus();
    else { const lib = $("#library"); if (lib) lib.focus(); }
    announce("Recently opened cleared");
  }

  // ---------- toast / live announcements ----------

  const toast = $("#toast");
  let toastTimer = 0;
  let toastSetTimer = 0;

  function announce(message) {
    if (!toast) return;
    clearTimeout(toastTimer);
    clearTimeout(toastSetTimer);
    // Empty first so an identical repeated message ("Link copied" twice) is re-announced.
    toast.textContent = "";
    toastSetTimer = setTimeout(() => {
      toast.textContent = message;
      toastTimer = setTimeout(() => { toast.textContent = ""; }, 3000);
    }, 50);
  }

  // ---------- search + filters ----------

  const form = $("#controls");
  const qInput = $("#q");
  const resultsEl = $("#results");
  const resetBtn = $("#resetFilters");
  const emptyState = $("#emptyState");
  const emptyTitle = emptyState ? $(".empty-title", emptyState) : null;
  const emptyTitleDefault = emptyTitle ? emptyTitle.textContent : "";

  const courses = $$(".course").map((el) => ({
    el,
    stage: el.dataset.stage || "",
    term: el.dataset.term || "",
    haystack: normalise(el.dataset.search || el.textContent),
    words: normalise(el.dataset.search || el.textContent).split(/[^\p{L}\p{N}]+/u).filter(Boolean),
    title: $(".course-title", el),
  }));
  const terms = $$(".term");
  const stages = $$(".stage");
  const total = courses.length;

  // Original title text, captured before any <mark> is inserted.
  const titleOriginals = new Map(courses.filter((c) => c.title).map((c) => [c.title, c.title.textContent]));
  const titleHighlightKey = new Map();

  function titleText(titleEl) {
    return titleOriginals.get(titleEl) ?? titleEl.textContent;
  }

  // Arabic letters have several written forms students type interchangeably (أ/إ/آ/ا, ى/ي, ة/ه),
  // plus optional diacritics and tatweel; fold them so "الاولى" finds "الأولى".
  function normalise(s) {
    return String(s)
      .toLowerCase()
      .replace(/[\u064B-\u0652\u0640]/g, "")
      .replace(/[أإآ]/g, "ا")
      .replace(/ى/g, "ي")
      .replace(/ة/g, "ه")
      .replace(/\s+/g, " ")
      .trim();
  }

  // "stage 1" / "year 1" / "sem 2" become single tokens matching the build's "stage1"/"semester2",
  // so the number can't match a different field (e.g. "Semester 1" when asking for stage 1).
  function tokenise(q) {
    const n = normalise(q)
      .replace(/\b(?:stage|year|level)\s*(\d)\b/g, "stage$1")
      .replace(/\b(?:semester|sem|term)\s*(\d)\b/g, "semester$1");
    // Punctuation-only tokens ("&", "-") can't match the word list and would empty the results.
    return n ? n.split(" ").filter((t) => /[\p{L}\p{N}]/u.test(t)) : [];
  }

  // Word-prefix match keeps short tokens precise ("2" finds "English Language 2", not every
  // "semester2"); longer tokens may also match mid-word ("base" → "Database").
  function matches(course, token) {
    return course.words.some((w) => w.startsWith(token)) || (token.length >= 3 && course.haystack.includes(token));
  }

  function radioValue(name) {
    const checked = form && form.querySelector(`input[name="${name}"]:checked`);
    return checked ? checked.value : "";
  }

  function setRadio(name, value) {
    if (!form) return;
    const radio = form.querySelector(`input[name="${name}"][value="${CSS.escape(value)}"]`);
    if (radio) radio.checked = true;
  }

  function readState() {
    return {
      q: qInput ? qInput.value : "",
      stage: radioValue("stage"),
      term: radioValue("term"),
    };
  }

  function isFiltered(state) {
    return Boolean(normalise(state.q) || state.stage || state.term);
  }

  // Pure computation: decide visibility for everything, touching no DOM, so the write
  // phase below is a single uninterrupted batch (no read/write interleaving).
  function computeVisibility(state) {
    const tokens = tokenise(state.q);
    const hasQuery = tokens.length > 0;
    const courseVisible = new Map();
    let shown = 0;

    for (const c of courses) {
      const ok =
        (!state.stage || c.stage === state.stage) &&
        (!state.term || c.term === state.term) &&
        tokens.every((t) => matches(c, t));
      courseVisible.set(c.el, ok);
      if (ok) shown++;
    }

    const termVisible = new Map();
    for (const term of terms) {
      const stageEl = term.closest(".stage");
      const stageOk = !state.stage || (stageEl && stageEl.dataset.stage === state.stage);
      const termOk = !state.term || term.dataset.term === state.term;
      const anyCourse = $$(".course", term).some((el) => courseVisible.get(el));
      const emptyOk = Boolean($(".term-empty", term)) && !hasQuery && stageOk && termOk;
      termVisible.set(term, anyCourse || emptyOk);
    }

    let emptyStageShown = false;
    const stageVisible = new Map();
    for (const stage of stages) {
      const anyCourse = $$(".course", stage).some((el) => courseVisible.get(el));
      const anyTerm = $$(".term", stage).some((el) => termVisible.get(el));
      const isEmptyStage = Boolean($(".stage-empty", stage));
      // An empty stage is real information ("nothing yet"), so show it when explicitly
      // selected, or in the pristine unfiltered view that mirrors the no-JS page.
      const emptyOk = isEmptyStage &&
        (state.stage === stage.dataset.stage || (!state.stage && !state.term && !hasQuery));
      const visible = anyCourse || anyTerm || emptyOk;
      if (visible && emptyOk && !anyCourse) emptyStageShown = true;
      stageVisible.set(stage, visible);
    }

    return { tokens, courseVisible, termVisible, stageVisible, shown, nothingVisible: shown === 0 && !emptyStageShown };
  }

  function setHidden(el, hidden) {
    if (el.hidden !== hidden) el.hidden = hidden;
  }

  function highlightTitle(titleEl, tokens) {
    const original = titleOriginals.get(titleEl);
    if (original == null) return;
    const key = tokens.join(" ");
    if (titleHighlightKey.get(titleEl) === key) return;
    titleHighlightKey.set(titleEl, key);

    const lower = original.toLowerCase();
    const ranges = [];
    for (const t of tokens) {
      let from = 0;
      let i;
      while ((i = lower.indexOf(t, from)) !== -1) {
        ranges.push([i, i + t.length]);
        from = i + t.length;
      }
    }
    if (!ranges.length) {
      if (titleEl.childElementCount || titleEl.textContent !== original) titleEl.textContent = original;
      return;
    }

    ranges.sort((a, b) => a[0] - b[0]);
    const merged = [ranges[0].slice()];
    for (const [s, e] of ranges.slice(1)) {
      const last = merged[merged.length - 1];
      if (s <= last[1]) last[1] = Math.max(last[1], e);
      else merged.push([s, e]);
    }

    // Text nodes only — the query never reaches an HTML parser.
    const frag = document.createDocumentFragment();
    let pos = 0;
    for (const [s, e] of merged) {
      if (s > pos) frag.append(original.slice(pos, s));
      const mark = document.createElement("mark");
      mark.textContent = original.slice(s, e);
      frag.append(mark);
      pos = e;
    }
    if (pos < original.length) frag.append(original.slice(pos));
    titleEl.replaceChildren(frag);
  }

  function resultsText(shown, filtered) {
    const noun = total === 1 ? "course" : "courses";
    return filtered ? `${shown} of ${total} ${noun}` : `${total} ${noun}`;
  }

  let resultsTimer = 0;
  function updateResults(text, immediate) {
    if (!resultsEl) return;
    clearTimeout(resultsTimer);
    // The DOM filters instantly; only the live region waits, so a screen reader hears the
    // settled count once instead of one announcement per keystroke.
    if (immediate) resultsEl.textContent = text;
    else resultsTimer = setTimeout(() => { resultsEl.textContent = text; }, 400);
  }

  function applyFilters({ immediateResults = false } = {}) {
    const state = readState();
    const filtered = isFiltered(state);
    const v = computeVisibility(state);

    for (const c of courses) {
      setHidden(c.el, !v.courseVisible.get(c.el));
      if (c.title) highlightTitle(c.title, v.tokens);
    }
    for (const t of terms) setHidden(t, !v.termVisible.get(t));
    for (const s of stages) setHidden(s, !v.stageVisible.get(s));

    if (emptyState) setHidden(emptyState, !v.nothingVisible);
    if (emptyTitle) {
      const q = state.q.trim();
      const text = q ? `No courses match “${q}”` : emptyTitleDefault;
      if (emptyTitle.textContent !== text) emptyTitle.textContent = text;
    }
    if (resetBtn) setHidden(resetBtn, !filtered);

    updateResults(resultsText(v.shown, filtered), immediateResults);
    return state;
  }

  // ---------- URL state ----------

  let urlTimer = 0;
  function writeUrl(state) {
    clearTimeout(urlTimer);
    // Debounced: Safari throws SecurityError past ~100 replaceState calls per 10s.
    urlTimer = setTimeout(() => {
      const params = new URLSearchParams(location.search);
      const q = state.q.trim();
      q ? params.set("q", q) : params.delete("q");
      state.stage ? params.set("stage", state.stage) : params.delete("stage");
      state.term ? params.set("term", state.term) : params.delete("term");
      const search = params.toString();
      // The hash is dropped on purpose: once the user filters, the URL describes the view,
      // and a stale #course would override these filters when the link is reopened.
      const url = location.pathname + (search ? `?${search}` : "");
      try { history.replaceState(history.state, "", url); } catch { /* URL sync is optional */ }
    }, 250);
  }

  function readUrl() {
    const params = new URLSearchParams(location.search);
    const q = params.get("q");
    const stage = params.get("stage");
    const term = params.get("term");
    if (qInput && q) qInput.value = q;
    if (stage && /^[1-4]$/.test(stage)) setRadio("stage", stage);
    if (term && /^[12]$/.test(term)) setRadio("term", term);
  }

  function clearControls() {
    if (qInput) qInput.value = "";
    setRadio("stage", "");
    setRadio("term", "");
  }

  function onFilterChange() {
    writeUrl(applyFilters());
  }

  // ---------- hash targets ----------

  let targetTimer = 0;
  let lastTarget = null;

  function hashTarget() {
    if (!location.hash || location.hash.length < 2) return null;
    let id;
    try { id = decodeURIComponent(location.hash.slice(1)); } catch { return null; }
    return document.getElementById(id);
  }

  function revealHashTarget({ scroll }) {
    const target = hashTarget();
    if (!target || !$("#library")?.contains(target)) return;

    // A shared #course link must win over leftover filters, or the recipient sees nothing.
    const wasHidden = Boolean(target.closest("[hidden]"));
    if (wasHidden) {
      clearControls();
      applyFilters({ immediateResults: true });
      clearTimeout(urlTimer);
      // Keep the hash (it's the point of the link), drop only the filter params.
      try { history.replaceState(history.state, "", location.pathname + location.hash); } catch { /* optional */ }
    }

    if (target.classList.contains("course")) {
      clearTimeout(targetTimer);
      if (lastTarget) lastTarget.classList.remove("is-target");
      target.classList.add("is-target");
      lastTarget = target;
      targetTimer = setTimeout(() => target.classList.remove("is-target"), 2500);
    }
    // The browser's fragment scroll ran (or failed) while filters hid the target, or ran
    // before ?q= filtering reshuffled the layout above it.
    if (wasHidden || scroll) target.scrollIntoView({ block: "start" });
  }

  // ---------- keyboard ----------

  function isApple() {
    const platform = (navigator.userAgentData && navigator.userAgentData.platform) || navigator.platform || "";
    return /Mac|iPhone|iPad|iPod|macOS/i.test(platform);
  }

  function onGlobalKeydown(e) {
    if (e.isComposing || e.keyCode === 229) return;
    if (!(e.ctrlKey || e.metaKey) || e.altKey || e.shiftKey) return;
    if ((e.key || "").toLowerCase() !== "k" || !qInput) return;
    e.preventDefault();
    qInput.focus();
    qInput.select();
  }

  function onSearchKeydown(e) {
    if (e.key !== "Escape" || e.isComposing) return;
    if (qInput.value) {
      // Own the clear so filtering + URL stay in sync on every engine (not all fire "input").
      e.preventDefault();
      qInput.value = "";
      onFilterChange();
    } else {
      qInput.blur();
    }
  }

  // ---------- library delegation: open/download tracking + share ----------

  function onLibraryActivate(e) {
    if (e.type === "auxclick" && e.button !== 1) return;
    const target = e.target instanceof Element ? e.target : null;
    if (!target) return;

    const share = target.closest("button.share[data-share]");
    if (share && e.type === "click") { shareCourse(share); return; }

    const link = target.closest("a.btn--primary, a[download]");
    const course = link && link.closest(".course");
    // Store only. Rendering now would insert the row above the reader mid-visit, and Safari
    // has no scroll anchoring, so the page would jump; the row appears on the next visit.
    if (course && course.id) rememberCourse(course.id);
  }

  function onRecentActivate(e) {
    if (e.type === "auxclick" && e.button !== 1) return;
    const li = e.target instanceof Element ? e.target.closest("li[data-id]") : null;
    // Store only; re-rendering now would destroy the link the user is still focused on.
    if (li) rememberCourse(li.dataset.id);
  }

  function isTouchPrimary() {
    return Boolean(window.matchMedia && window.matchMedia("(pointer: coarse)").matches);
  }

  function copyWithTextarea(text, returnFocusTo) {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.setAttribute("readonly", "");
    ta.style.position = "fixed";
    ta.style.top = "0";
    ta.style.left = "-9999px";
    ta.style.opacity = "0";
    document.body.append(ta);
    let ok = false;
    try {
      ta.select();
      ok = document.execCommand("copy");
    } catch {
      ok = false;
    } finally {
      ta.remove();
      if (returnFocusTo) returnFocusTo.focus();
    }
    return ok;
  }

  async function copyText(text, button) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      try {
        await navigator.clipboard.writeText(text);
        return true;
      } catch { /* permission denied or insecure context: try the legacy path */ }
    }
    return copyWithTextarea(text, button);
  }

  function showCopied(button) {
    button.classList.add("is-copied");
    let done = button.nextElementSibling;
    if (!done || !done.classList.contains("share-done")) {
      done = document.createElement("span");
      done.className = "share-done";
      done.setAttribute("aria-hidden", "true");
      done.textContent = "Copied";
      button.after(done);
    }
    clearTimeout(Number(button.dataset.copiedTimer));
    button.dataset.copiedTimer = String(setTimeout(() => {
      button.classList.remove("is-copied");
      done.remove();
      delete button.dataset.copiedTimer;
    }, 2000));
    announce("Link copied");
  }

  async function shareCourse(button) {
    const id = button.dataset.share;
    const url = location.origin + location.pathname + "#" + id;
    const course = findCourse(id);
    const titleEl = course && $(".course-title", course);
    const title = titleEl ? titleText(titleEl) : document.title;

    try {
      if (navigator.share && isTouchPrimary()) {
        try {
          await navigator.share({ title, url });
        } catch (err) {
          if (err && err.name === "AbortError") return; // user dismissed the sheet
          throw err;
        }
        return;
      }
      if (await copyText(url, button)) showCopied(button);
      else announce("Couldn't copy the link");
    } catch {
      announce("Couldn't copy the link");
    }
  }

  // ---------- theme ----------

  const themeToggle = $("#themeToggle");
  const themeValue = $("#themeValue");

  function currentTheme() {
    const t = document.documentElement.dataset.theme;
    return t === "light" || t === "dark" ? t : "system";
  }

  function themeLabel(theme) {
    return theme.charAt(0).toUpperCase() + theme.slice(1);
  }

  // The head has one theme-color per OS scheme (media-queried). A manual theme must override
  // both, and "system" must restore the originals, or the browser bar disagrees with the page.
  const themeMetas = [...document.querySelectorAll('meta[name="theme-color"]')];
  themeMetas.forEach((meta) => { meta.dataset.original = meta.content; });

  function syncThemeColorMeta() {
    if (!themeMetas.length || !document.body) return;
    const manual = currentTheme() !== "system";
    const bg = getComputedStyle(document.body).backgroundColor;
    themeMetas.forEach((meta) => {
      meta.content = manual && bg ? bg : meta.dataset.original;
    });
  }

  function setTheme(theme) {
    const root = document.documentElement;
    if (theme === "system") {
      delete root.dataset.theme;
      storageRemove("theme");
    } else {
      root.dataset.theme = theme;
      storageSet("theme", theme);
    }
    if (themeValue) themeValue.textContent = themeLabel(theme);
    syncThemeColorMeta();
  }

  function cycleTheme() {
    const next = THEMES[(THEMES.indexOf(currentTheme()) + 1) % THEMES.length];
    setTheme(next);
    announce(`Theme: ${themeLabel(next)}`);
  }

  // ---------- init ----------

  renderRecent();

  // Two frames: the first paint must happen with transitions off (see styles.css reset layer).
  requestAnimationFrame(() => requestAnimationFrame(() => document.documentElement.classList.add("ready")));

  if (themeValue) themeValue.textContent = themeLabel(currentTheme());
  syncThemeColorMeta();
  if (themeToggle) themeToggle.addEventListener("click", cycleTheme);

  if (isApple()) {
    const hint = $(".search-hint");
    if (hint) hint.textContent = "⌘K";
  }

  if (form) {
    readUrl();
    applyFilters({ immediateResults: true });

    form.addEventListener("submit", (e) => e.preventDefault());
    form.addEventListener("input", onFilterChange);
    // Radios fire "change" (and "input"); listening to both is harmless — applyFilters is idempotent.
    form.addEventListener("change", onFilterChange);
    form.addEventListener("reset", () => {
      // "reset" fires before the controls are restored, so filter on the next task.
      setTimeout(() => {
        onFilterChange();
        if (qInput && document.activeElement === document.body) qInput.focus();
      }, 0);
    });
  }

  if (resetBtn) {
    // The button hides itself once filters clear; keep focus from falling to <body>.
    resetBtn.addEventListener("click", () => setTimeout(() => qInput && qInput.focus(), 0));
  }

  const emptyReset = $("#emptyReset");
  if (emptyReset) {
    emptyReset.addEventListener("click", () => {
      if (form) form.reset();
      clearControls();
      onFilterChange();
      if (qInput) qInput.focus();
    });
  }

  if (qInput) qInput.addEventListener("keydown", onSearchKeydown);
  document.addEventListener("keydown", onGlobalKeydown);

  const library = $("#library");
  if (library) {
    library.addEventListener("click", onLibraryActivate);
    library.addEventListener("auxclick", onLibraryActivate);
  }
  if (recentList) {
    recentList.addEventListener("click", onRecentActivate);
    recentList.addEventListener("auxclick", onRecentActivate);
  }

  revealHashTarget({ scroll: Boolean(location.hash) && Boolean(location.search) });
  window.addEventListener("hashchange", () => revealHashTarget({ scroll: false }));
})();
