// Search and filters for the static library generated by tools/build.mjs (ADR 0001).
// Everything here is optional: with JS off, index.html is already the full, navigable library.
(() => {
  "use strict";

  const $ = (sel, root = document) => root.querySelector(sel);
  const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));

  // ---------- search + filters ----------

  const form = $("#controls");
  const qInput = $("#q");
  const resultsEl = $("#results");
  const resetBtn = $("#resetFilters");
  const emptyState = $("#emptyState");
  const emptyTitle = emptyState ? $(".empty-title", emptyState) : null;
  const emptyTitleDefault = emptyTitle ? emptyTitle.textContent : "";

  const courses = $$(".course").map((el) => ({
    el,
    stage: el.dataset.stage || "",
    term: el.dataset.term || "",
    haystack: normalise(el.dataset.search || el.textContent),
    words: normalise(el.dataset.search || el.textContent).split(/[^\p{L}\p{N}]+/u).filter(Boolean),
    title: $(".course-title", el),
  }));
  const terms = $$(".term");
  const stages = $$(".stage");
  const total = courses.length;

  // Original title text, captured before any <mark> is inserted.
  const titleOriginals = new Map(courses.filter((c) => c.title).map((c) => [c.title, c.title.textContent]));
  const titleHighlightKey = new Map();

  // Arabic letters have several written forms students type interchangeably (أ/إ/آ/ا, ى/ي, ة/ه),
  // plus optional diacritics and tatweel; fold them so "الاولى" finds "الأولى".
  function normalise(s) {
    return String(s)
      .toLowerCase()
      .replace(/[\u064B-\u0652\u0640]/g, "")
      .replace(/[أإآ]/g, "ا")
      .replace(/ى/g, "ي")
      .replace(/ة/g, "ه")
      .replace(/\s+/g, " ")
      .trim();
  }

  // "stage 1" / "year 1" / "sem 2" become single tokens matching the build's "stage1"/"semester2",
  // so the number can't match a different field (e.g. "Semester 1" when asking for stage 1).
  function tokenise(q) {
    const n = normalise(q)
      .replace(/\b(?:stage|year|level)\s*(\d)\b/g, "stage$1")
      .replace(/\b(?:semester|sem|term)\s*(\d)\b/g, "semester$1");
    // Punctuation-only tokens ("&", "-") can't match the word list and would empty the results.
    return n ? n.split(" ").filter((t) => /[\p{L}\p{N}]/u.test(t)) : [];
  }

  // Word-prefix match keeps short tokens precise ("2" finds "English Language 2", not every
  // "semester2"); longer tokens may also match mid-word ("base" → "Database").
  function matches(course, token) {
    return course.words.some((w) => w.startsWith(token)) || (token.length >= 3 && course.haystack.includes(token));
  }

  function radioValue(name) {
    const checked = form && form.querySelector(`input[name="${name}"]:checked`);
    return checked ? checked.value : "";
  }

  function setRadio(name, value) {
    if (!form) return;
    const radio = form.querySelector(`input[name="${name}"][value="${CSS.escape(value)}"]`);
    if (radio) radio.checked = true;
  }

  function readState() {
    return {
      q: qInput ? qInput.value : "",
      stage: radioValue("stage"),
      term: radioValue("term"),
    };
  }


  // Pure computation: decide visibility for everything, touching no DOM, so the write
  // phase below is a single uninterrupted batch (no read/write interleaving).
  function computeVisibility(state) {
    const tokens = tokenise(state.q);
    const hasQuery = tokens.length > 0;
    const courseVisible = new Map();
    let shown = 0;

    for (const c of courses) {
      const ok =
        (!state.stage || c.stage === state.stage) &&
        (!state.term || c.term === state.term) &&
        tokens.every((t) => matches(c, t));
      courseVisible.set(c.el, ok);
      if (ok) shown++;
    }

    const termVisible = new Map();
    for (const term of terms) {
      const stageEl = term.closest(".stage");
      const stageOk = !state.stage || (stageEl && stageEl.dataset.stage === state.stage);
      const termOk = !state.term || term.dataset.term === state.term;
      const anyCourse = $$(".course", term).some((el) => courseVisible.get(el));
      const emptyOk = Boolean($(".term-empty", term)) && !hasQuery && stageOk && termOk;
      termVisible.set(term, anyCourse || emptyOk);
    }

    let emptyStageShown = false;
    const stageVisible = new Map();
    for (const stage of stages) {
      const anyCourse = $$(".course", stage).some((el) => courseVisible.get(el));
      const anyTerm = $$(".term", stage).some((el) => termVisible.get(el));
      const isEmptyStage = Boolean($(".stage-empty", stage));
      // An empty stage is real information ("nothing yet"), so show it when explicitly
      // selected, or in the pristine unfiltered view that mirrors the no-JS page.
      const emptyOk = isEmptyStage &&
        (state.stage === stage.dataset.stage || (!state.stage && !state.term && !hasQuery));
      const visible = anyCourse || anyTerm || emptyOk;
      if (visible && emptyOk && !anyCourse) emptyStageShown = true;
      stageVisible.set(stage, visible);
    }

    return { tokens, courseVisible, termVisible, stageVisible, shown, nothingVisible: shown === 0 && !emptyStageShown };
  }

  function setHidden(el, hidden) {
    if (el.hidden !== hidden) el.hidden = hidden;
  }

  function highlightTitle(titleEl, tokens) {
    const original = titleOriginals.get(titleEl);
    if (original == null) return;
    const key = tokens.join(" ");
    if (titleHighlightKey.get(titleEl) === key) return;
    titleHighlightKey.set(titleEl, key);

    const lower = original.toLowerCase();
    const ranges = [];
    for (const t of tokens) {
      let from = 0;
      let i;
      while ((i = lower.indexOf(t, from)) !== -1) {
        ranges.push([i, i + t.length]);
        from = i + t.length;
      }
    }
    if (!ranges.length) {
      if (titleEl.childElementCount || titleEl.textContent !== original) titleEl.textContent = original;
      return;
    }

    ranges.sort((a, b) => a[0] - b[0]);
    const merged = [ranges[0].slice()];
    for (const [s, e] of ranges.slice(1)) {
      const last = merged[merged.length - 1];
      if (s <= last[1]) last[1] = Math.max(last[1], e);
      else merged.push([s, e]);
    }

    // Text nodes only — the query never reaches an HTML parser.
    const frag = document.createDocumentFragment();
    let pos = 0;
    for (const [s, e] of merged) {
      if (s > pos) frag.append(original.slice(pos, s));
      const mark = document.createElement("mark");
      mark.textContent = original.slice(s, e);
      frag.append(mark);
      pos = e;
    }
    if (pos < original.length) frag.append(original.slice(pos));
    titleEl.replaceChildren(frag);
  }

  function resultsText(shown, searching) {
    const noun = total === 1 ? "course" : "courses";
    // Only a search needs a count; a stage choice is already obvious from what's open.
    return searching ? `${shown} of ${total} ${noun}` : "";
  }

  // ---------- stage drop-downs ----------
  // While searching or picking a stage, the stages that hold results open by themselves so
  // the matches are visible. When the filter goes away, only those auto-opened stages close
  // again; a stage the student opened (or closed) by hand is left as they set it.

  const autoOpened = new Set();
  const expectedOpen = new Map();

  function setOpen(details, open) {
    expectedOpen.set(details, open);
    details.open = open;
  }

  function syncStageOpen(state, hasQuery) {
    for (const s of stages) {
      const want = !s.hidden && (hasQuery || Boolean(state.stage));
      if (want && !s.open) {
        autoOpened.add(s);
        setOpen(s, true);
      } else if (!want && autoOpened.has(s)) {
        autoOpened.delete(s);
        setOpen(s, false);
      }
    }
  }

  for (const s of stages) {
    s.addEventListener("toggle", () => {
      // A toggle we didn't cause means the student took over this stage.
      if (expectedOpen.get(s) !== s.open) autoOpened.delete(s);
      expectedOpen.set(s, s.open);
    });
  }

  // name="course" already makes course rows exclusive in current browsers; this covers older ones.
  if (!("name" in HTMLDetailsElement.prototype)) {
    document.addEventListener("toggle", (e) => {
      const d = e.target;
      if (!(d instanceof HTMLDetailsElement) || !d.open || !d.classList.contains("course-item")) return;
      for (const other of $$(".course-item[open]")) if (other !== d) other.open = false;
    }, true);
  }

  let resultsTimer = 0;
  function updateResults(text, immediate) {
    if (!resultsEl) return;
    clearTimeout(resultsTimer);
    // The DOM filters instantly; only the live region waits, so a screen reader hears the
    // settled count once instead of one announcement per keystroke.
    // Clearing is immediate: a stale "1 of 37" lingering after the search is gone is just noise.
    if (immediate || !text) resultsEl.textContent = text;
    else resultsTimer = setTimeout(() => { resultsEl.textContent = text; }, 400);
  }

  function applyFilters({ immediateResults = false } = {}) {
    const state = readState();
    const v = computeVisibility(state);

    for (const c of courses) {
      setHidden(c.el, !v.courseVisible.get(c.el));
      if (c.title) highlightTitle(c.title, v.tokens);
    }
    for (const t of terms) setHidden(t, !v.termVisible.get(t));
    for (const s of stages) setHidden(s, !v.stageVisible.get(s));

    if (emptyState) setHidden(emptyState, !v.nothingVisible);
    if (emptyTitle) {
      const q = state.q.trim();
      const text = q ? `No courses match “${q}”` : emptyTitleDefault;
      if (emptyTitle.textContent !== text) emptyTitle.textContent = text;
    }
    const searching = v.tokens.length > 0;
    // "Clear search" is for the search box only; choosing a stage needs no clear button.
    if (resetBtn) setHidden(resetBtn, !state.q.trim());
    syncStageOpen(state, searching);

    updateResults(resultsText(v.shown, searching), immediateResults);
    return state;
  }

  // ---------- URL state ----------

  let urlTimer = 0;
  function writeUrl(state) {
    clearTimeout(urlTimer);
    // Debounced: Safari throws SecurityError past ~100 replaceState calls per 10s.
    urlTimer = setTimeout(() => {
      const params = new URLSearchParams(location.search);
      const q = state.q.trim();
      q ? params.set("q", q) : params.delete("q");
      state.stage ? params.set("stage", state.stage) : params.delete("stage");
      state.term ? params.set("term", state.term) : params.delete("term");
      const search = params.toString();
      // The hash is dropped on purpose: once the user filters, the URL describes the view,
      // and a stale #course would override these filters when the link is reopened.
      const url = location.pathname + (search ? `?${search}` : "");
      try { history.replaceState(history.state, "", url); } catch { /* URL sync is optional */ }
    }, 250);
  }

  function readUrl() {
    const params = new URLSearchParams(location.search);
    const q = params.get("q");
    const stage = params.get("stage");
    const term = params.get("term");
    if (qInput && q) qInput.value = q;
    if (stage && /^[1-4]$/.test(stage)) setRadio("stage", stage);
    if (term && /^[12]$/.test(term)) setRadio("term", term);
  }

  function clearControls() {
    if (qInput) qInput.value = "";
    setRadio("stage", "");
    setRadio("term", "");
  }

  function onFilterChange() {
    writeUrl(applyFilters());
  }

  // ---------- hash targets ----------

  let targetTimer = 0;
  let lastTarget = null;

  function hashTarget() {
    if (!location.hash || location.hash.length < 2) return null;
    let id;
    try { id = decodeURIComponent(location.hash.slice(1)); } catch { return null; }
    return document.getElementById(id);
  }

  function revealHashTarget({ scroll }) {
    const target = hashTarget();
    if (!target || !$("#library")?.contains(target)) return;

    // A shared #course link must win over leftover filters, or the recipient sees nothing.
    const wasHidden = Boolean(target.closest("[hidden]"));
    if (wasHidden) {
      clearControls();
      applyFilters({ immediateResults: true });
      clearTimeout(urlTimer);
      // Keep the hash (it's the point of the link), drop only the filter params.
      try { history.replaceState(history.state, "", location.pathname + location.hash); } catch { /* optional */ }
    }

    // Open every drop-down between the page and the target so it can actually be seen.
    let opened = false;
    for (let d = target.closest("details"); d; d = d.parentElement && d.parentElement.closest("details")) {
      if (!d.open) { setOpen(d, true); opened = true; }
    }
    const item = target.classList.contains("course") ? $(".course-item", target) : null;
    if (item && !item.open) { item.open = true; opened = true; }
    if (target.matches("details.stage") && !target.open) { setOpen(target, true); opened = true; }

    if (target.classList.contains("course")) {
      clearTimeout(targetTimer);
      if (lastTarget) lastTarget.classList.remove("is-target");
      target.classList.add("is-target");
      lastTarget = target;
      targetTimer = setTimeout(() => target.classList.remove("is-target"), 2500);
    }
    // The browser's fragment scroll ran (or failed) while filters hid the target, or ran
    // before ?q= filtering reshuffled the layout above it.
    if (wasHidden || scroll || opened) target.scrollIntoView({ block: "start" });
  }

  // ---------- keyboard ----------

  function onSearchKeydown(e) {
    if (e.key !== "Escape" || e.isComposing) return;
    if (qInput.value) {
      // Own the clear so filtering + URL stay in sync on every engine (not all fire "input").
      e.preventDefault();
      qInput.value = "";
      onFilterChange();
    } else {
      qInput.blur();
    }
  }

  // ---------- init ----------

  // Two frames: the first paint must happen with transitions off (see styles.css reset layer).
  requestAnimationFrame(() => requestAnimationFrame(() => document.documentElement.classList.add("ready")));

  if (form) {
    readUrl();
    applyFilters({ immediateResults: true });

    form.addEventListener("submit", (e) => e.preventDefault());
    form.addEventListener("input", onFilterChange);
    // Radios fire "change" (and "input"); listening to both is harmless — applyFilters is idempotent.
    form.addEventListener("change", onFilterChange);
  }

  // Both buttons clear the search only (the stage choice stays) and keep focus in the field,
  // since the button that was clicked hides itself.
  function clearSearch() {
    if (!qInput) return;
    qInput.value = "";
    onFilterChange();
    qInput.focus();
  }

  if (resetBtn) resetBtn.addEventListener("click", clearSearch);
  const emptyReset = $("#emptyReset");
  if (emptyReset) emptyReset.addEventListener("click", clearSearch);

  // On phones the map scrolls sideways; a scrollable region must be reachable by keyboard,
  // but on desktop (no overflow) an empty tab stop would just be in the way.
  const mapGrid = $("#mapGrid");
  function syncMapScroll() {
    if (!mapGrid) return;
    const scrolls = mapGrid.scrollWidth > mapGrid.clientWidth + 1;
    if (scrolls) { mapGrid.tabIndex = 0; mapGrid.setAttribute("role", "region"); }
    else { mapGrid.removeAttribute("tabindex"); mapGrid.removeAttribute("role"); }
  }
  syncMapScroll();
  window.addEventListener("resize", syncMapScroll);
  const mapDetails = $("#map");
  if (mapDetails) mapDetails.addEventListener("toggle", syncMapScroll);

  // Printing: closed drop-downs would print as bare headings, so open the stages for the
  // printout and put them back afterwards.
  let printOpened = [];
  window.addEventListener("beforeprint", () => {
    printOpened = stages.filter((s) => !s.open && !s.hidden);
    printOpened.forEach((s) => setOpen(s, true));
  });
  window.addEventListener("afterprint", () => {
    printOpened.forEach((s) => setOpen(s, false));
    printOpened = [];
  });

  if (qInput) qInput.addEventListener("keydown", onSearchKeydown);

  revealHashTarget({ scroll: Boolean(location.hash) && Boolean(location.search) });
  window.addEventListener("hashchange", () => revealHashTarget({ scroll: false }));
})();
